#!/usr/bin/env bash

bundler_version="1.1.0"
rspec_version="2.6.0"

source "$HOME/.rvm/scripts/rvm"

function install_ruby_if_needed() {
  echo "Checking for $1..."
  if ! rvm list rubies | grep $1 > /dev/null; then
    rvm install $1
  fi
}
function switch_ruby() {
  install_ruby_if_needed $1 && rvm use $1
}

function install_bundler_if_needed() {
  echo "Checking for Bundler $bundler_version..."
  if ! gem list --installed bundler --version "$bundler_version" > /dev/null; then
    gem install bundler --version "$bundler_version" --source http://mirrors.squareup.com/rubygems
  fi
}

function install_rspec_if_needed() {
  echo "Checking for rspec $rspec_version..."
  if ! gem list --installed rspec --version "$rspec_version" > /dev/null; then
    gem install rspec --version "$rspec_version" --source http://mirrors.squareup.com/rubygems
  fi
}

function update_gems_if_needed() {
  echo "Installing gems..."
  bundle check || bundle install
}

function run_tests() {
  bundle exec rake spec:setup
  rspec spec/suite.rb # Cannot be bundle exec'd
}

function prepare_and_run() {
  switch_ruby $1 &&
  install_bundler_if_needed &&
  install_rspec_if_needed &&
  update_gems_if_needed &&
  run_tests
}

function mark_latest_green_build() {
  git checkout -B latest-green-build HEAD
  git push -f origin HEAD:latest-green-build
}

prepare_and_run "1.9.3-p0" &&
mark_latest_green_build
